name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      debug_mode:
        description: 'Enable extra logging?'
        required: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }}"
          echo "Debug mode is ${{ github.event.inputs.debug_mode }}"
